### ISSUE TITLE
internal/oboe: Oboe fails to compile with NDK 30 (AAudio type redefinitions and AAudio_DeviceType static_assert)

### ISSUE THREAD

**Issue by hajimehoshi** [hajimehoshi/oto#287]
The vendored Oboe in `internal/oboe` (Oboe 1.10.0, see `internal/oboe/gen.go`) does not compile with Android NDK 30.0.15729638.

This is an upstream Oboe bug, reported at google/oboe#2406. Oto is affected because it vendors the same sources verbatim and compiles them with cgo on Android (`internal/oboe/binding_android.go` does not define `OBOE_NO_INCLUDE_AAUDIO`, so the NDK's `<aaudio/AAudio.h>` declarations are in effect).

## Errors

```
redefinition of 'AAudio_FallbackMode'
redefinition of 'AAudio_StretchMode'
redefinition of 'AAudioPlaybackParameters'
static assertion failed due to requirement 'std::is_same<int, AAudio_DeviceType>::value': AAudio_DeviceType must be int32_t
```

## Cause

Both problems come from version guards that assume NDK 30 does not yet declare these AAudio APIs, while NDK 30.0.15729638 does.

* `internal/oboe/oboe_aaudio_AAudioLoader_android.h:116` defines `AAudio_FallbackMode`, `AAudio_StretchMode`, `AAudioPlaybackParameters` and `AAudioStream_partialDataCallback` under `#if OBOE_USING_NDK && __NDK_MAJOR__ <= 30`. The NDK already declares them, so they are redefined. The upstream source carries a `// TODO: find the first NDK version containing the following values` comment right above this guard, so the bound was a placeholder.
* `internal/oboe/oboe_aaudio_AAudioLoader_android.cpp:592` runs `ASSERT_INT32(AAudio_DeviceType)` under `#if __NDK_MAJOR__ >= 30`. In this NDK, `AAudio_DeviceType` is an enum with an explicit underlying type rather than a plain `typedef int32_t`, so `std::is_same<int32_t, AAudio_DeviceType>` is false and the `static_assert` fires.

## Resolution

Nothing to fix in Oto's own code. The fix belongs upstream; once it lands in an Oboe release, re-running `go generate ./internal/oboe` to pull in the newer version should be enough. A local patch of the two guards is possible in the meantime if a fix is wanted before then.

## Note

This has not been reproduced with a local NDK 30 build. The error messages and the diagnosis come from the upstream report combined with an inspection of the vendored sources, which are identical to the upstream ones at the reported lines.

---

Filed by Claude (Claude Code) on behalf of @hajimehoshi.

**Comment by hajimehoshi** [comment]
Reproduced and confirmed against the NDK from the upstream report (`Pkg.Revision = 30.0.15729638-beta2`, `__NDK_MAJOR__ 30`), so the "not reproduced" note in the description above no longer applies.

Building the unmodified sources for `android/arm64` fails with exactly the four reported errors:

```
oboe_aaudio_AAudioLoader_android.h:117:14: error: redefinition of 'AAudio_FallbackMode'
oboe_aaudio_AAudioLoader_android.h:123:14: error: redefinition of 'AAudio_StretchMode'
oboe_aaudio_AAudioLoader_android.h:128:16: error: redefinition of 'AAudioPlaybackParameters'
oboe_aaudio_AAudioLoader_android.cpp:592:5: error: static assertion failed due to requirement 'std::is_same<int, AAudio_DeviceType>::value': AAudio_DeviceType must be int32_t
```

## Correction about `AAudioStream_partialDataCallback`

It is tempting to read the error list as saying NDK 30 declares only three of the four types guarded by `#if OBOE_USING_NDK && __NDK_MAJOR__ <= 30`. It declares all four: `AAudioStream_partialDataCallback` is at `AAudio.h:1766` in this NDK. It stays off the error list only because it is a `typedef`, and redeclaring a typedef with the same type is legal C++, unlike the enum and struct redefinitions.

So the whole block belongs behind `< 30`; no need to keep the callback separate.

## Fix

Two hunks, applied to the vendored files:

```diff
 // TODO: find the first NDK version containing the following values
-#if OBOE_USING_NDK && __NDK_MAJOR__ <= 30
+#if OBOE_USING_NDK && __NDK_MAJOR__ < 30
```

```diff
 #if __NDK_MAJOR__ >= 30
 
-    ASSERT_INT32(AAudio_DeviceType);
     static_assert((int32_t)DeviceType::BuiltinEarpiece == AAUDIO_DEVICE_BUILTIN_EARPIECE, ERRMSG);
```

Dropping the assert is safe: the surrounding `static_assert`s cast to `int32_t` explicitly, and the only other uses of the type are `static_cast<AAudio_DeviceType>(...)` in `oboe_aaudio_AAudioExtensions_android.h`, which work on an enum.

Since `internal/oboe/oboe_*.{cpp,h}` are generator output, the change belongs in `internal/oboe/gen.go` as a replacement applied while copying, not in the generated files, so that `go generate ./internal/oboe` reproduces it. Erroring out when a replacement no longer matches also means a future `oboeVersion` bump that picks up an upstream fix fails loudly instead of silently doing nothing.

Build results with this applied:

| NDK | android/arm64 | android/arm |
| --- | --- | --- |
| 30.0.15729638-beta2 | ok | ok |
| 28.2.13676358 | ok | ok |

---

Posted by Claude (Claude Code), on behalf of @hajimehoshi.
