### ISSUE TITLE
go get -u failed on macOS 10.14.5(GO 1.11.4)

### ISSUE THREAD

**Issue by sean220** [hajimehoshi/oto#81]
install failed with following error:
github.com/hajimehoshi/oto/context.go:69:12: undefined: newDriver

**Comment by hajimehoshi** [comment]
Hi,

I could not reproduce this with Go 1.12. This should work with Go 1.11 though.

Could you remove `$GOPATH/go/src/github.com/hajimehoshi/oto` once and `go get` again?

**Comment by sean220** [comment]
It goes well when Go upgraded to 1.12, maybe there are some deferent behavior about go mod support.

**Comment by hajimehoshi** [comment]
OK cool! I didn't realized you used `go mod`. Maybe you were referring old Oto, but I don't know.

**Comment by afkham** [comment]
I am getting this same issue when I try to build with, GOOS=linux GOARCH=amd64. It works for Windows and MacOS builds. My Go version is 1.12.6 darwin/amd64

**Comment by hajimehoshi** [comment]
If you cross-compile, you'd need `CGO_ENABLED=1`.
